### ISSUE TITLE
How force Gtk/DecorationLayout "icon:minimize,maximize,close" to Gtk/DecorationLayout "menu"

### ISSUE THREAD

**Issue by nigelwarning** [derat/xsettingsd#18]
Hello,

I want my GTK apps not to use titlebars. Everythimg I change the decorationlayout, reboot, the xsettingsd.conf file reverts back to the icon:minimize..
I want to let it stay without these buttons. How can i do this?

Thanks!

**Comment by derat** [comment]
Hmm, so the content of your `xsettingsd.conf` file is changing when you reboot? Is there any chance that something else on your system is rewriting it?

**Comment by nigelwarning** [comment]
Fixed it by going to Window Decorations > Toolbar settings in KDE Plasma.

**Comment by derat** [comment]
Hmm, KDE might provide its own XSETTINGS implementation (are you also running [xsettings-kde](https://github.com/KDE/xsettings-kde)?). If both xsettingsd and another daemon implementing XSETTINGS are running, you'll probably see weird behavior depending on the order in which they start -- only the one that starts later will work.
