### ISSUE TITLE
Changing font type/size?

### ISSUE THREAD

**Issue by BFox89** [derat/xsettingsd#25]
I can't seem to find the option to configure `gtk-font-name`. I think it would be nice to have.
Something like:
`Net/FontName 'Ubuntu 12'`

**Comment by derat** [comment]
That would be up to GTK -- xsettingsd just provides a generic way to set properties that toolkits/programs/etc. use for configuration.

https://www.freedesktop.org/wiki/Specifications/XSettingsRegistry/ suggests that `Gtk/FontName` is probably what you're looking for, though.

GTK uses many sources for configuration, so you may need to make sure that whatever you configure via xsettingsd isn't overridden somewhere else. I documented the sources that I'm aware of at https://github.com/derat/font-config-info#readme, but note that it's seven years old. I wouldn't be surprised if several more ways of configuring fonts have been added in the meantime. :-/

**Comment by derat** [comment]
Please leave another comment if `Gtk/FontName` didn't work.
