### ISSUE TITLE
404 for https://developer.gnome.org/gtk/unstable/GtkSettings.html

### ISSUE THREAD

**Issue by ru2saig** [derat/xsettingsd#26]
Getting a 404 when I tried to open it.

I found this: https://developer-old.gnome.org/gtk3/stable/GtkSettings.html
Looking at https://developer.gnome.org/gtk/unstable/GtkSettings.html (with Wayback Machine: https://web.archive.org/web/20210507005358/http://developer.gnome.org/gtk3/unstable/GtkSettings.html), it seems that it's the same page moved to a different address.

Or how about this? https://docs.gtk.org/gtk3/class.Settings.html. I find this one is not a single page like the two links above, which I don't prefer.

Thoughts?

**Comment by derat** [comment]
Thanks for letting me know and finding the new location! I've updated the link on https://github.com/derat/xsettingsd/wiki/Settings.

I agree that https://developer-old.gnome.org/gtk3/stable/GtkSettings.html seems better. It also seems to have more information than https://docs.gtk.org/gtk3/class.Settings.html, e.g. https://developer-old.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-cursor-theme-size says "Size to use for cursors, or 0 to use the default size." but https://docs.gtk.org/gtk3/property.Settings.gtk-cursor-theme-size.html just says "No description available." (I'm not sure if that property can be set via XSETTINGS, but I also see this for some other properties like `gtk-cursor-theme-name`.)
