### ISSUE TITLE
locate, test and add more avilable xsettings as documentation

### ISSUE THREAD

**Issue by Quantenzitrone** [derat/xsettingsd#28]
I have read the [Xsettings Freedesktop Specification](https://specifications.freedesktop.org/xsettings-spec/xsettings-latest.html#manager-behavior) and am not really able to find documentation about available settings online.

The specification states:
> Names beginning with 'Net/' and case variants of that string are reserved and must not be used without prior agreement.

But there is no documentation on how or where to find or do these agreements.

I also get that everything else is depending on the specific Application(-framework) and i can likely find documentation there.
For example the GTK settings from the [documentation](https://docs.gtk.org/gtk4/class.Settings.html) can probably be translated directly, by changing the first `-` to a `/` and converting the rest to UpperCamelCase/PascalCase.
But I am also a bit lost there: What about Xft? Xft stands for X font library and the only documentation i can find is [the Freedesktop Specification](https://www.freedesktop.org/wiki/Software/Xft/). The GTK documentation only provides the options, that are already in the Wiki. Unless I or someone else finds anything else, I'll just guess that's it.

I'm sorry if this not the right place for asking this.

**Comment by derat** [comment]
It's a good question! Unfortunately, I don't remember there being much in the way of documentation when I was looking at this. :-(

I documented the settings that I could find at <https://github.com/derat/xsettingsd/wiki/Settings> (I don't think Markdown was popular at the time, hence the weird GitHub Wiki). I think I mostly figured them out through a combination of grepping through GTK+ source code and trial and error. It looks like there's a list (from 2013?) at <https://www.freedesktop.org/wiki/Specifications/XSettingsRegistry/> that lists some `Net/`- and `Xft/`-prefixed settings, too.

**Comment by Quantenzitrone** [comment]
Thanks a lot!
I could also find [this example xsettingsd config in someones blog](https://m4he.gitlab.io/linux-theming-compendium/appendix/#full-xsettingsd-configuration-example), maybe we can expand the wiki.

**Comment by Quantenzitrone** [comment]
Wait, (how) can i expand the wiki? I can clone it locally, but i probably won't be able to push. I can't clone it on GitHub, apparently.

**Comment by derat** [comment]
I'm in the process of moving those wiki pages into the README.md file so it's easier to make changes.

**Comment by Quantenzitrone** [comment]
Ok, so i could confirm these settings on my machine so far:
```
Net/ThemeName
Net/IconThemeName
Net/DoubleClickTime
Net/DoubleClickDistance
Net/DoubleClickTime
Net/DndDragThreshold
Net/CursorBlink
Net/CursorBlinkTime

Gtk/DecorationLayout
Gtk/FontName

Xft/Antialias
Xft/RGBA
Xft/Hinting
Xft/HintStyle
```

**Comment by derat** [comment]
Okay, the table is in README.md now.

**Comment by derat** [comment]
Thanks!
